# Generated by Django 2.2.4 on 2019-08-24 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('cycle_type', models.PositiveSmallIntegerField(choices=[(0, 'Kids Bike'), (1, 'Moutain Bike'), (2, 'Hybrid/Comfort Bike'), (3, 'Road Bike'), (4, 'RiverSide Bike')], default=0)),
                ('cycling_id', models.PositiveSmallIntegerField(verbose_name=(4454833, 1234590, 3454264, 4563361, 6754535, 8094518, 3763781, 6583190, 3453147, 8974225, 7013035, 7024599, 2563594, 2344971, 9741381, 5463099, 7654545, 3543269, 6452786, 6784484, 3493042, 1282865, 8761061, 4534883, 4734847, 5464484, 2534222, 6544414, 5494239, 1541964, 6753571, 3451847, 9451334, 7864885, 2431831, 8764868, 4561940, 4322491, 5674415, 4563196, 5674461, 7893769, 6784540, 9803389, 9083034, 8904822, 7894993, 7893575))),
                ('cycling_Reason', models.PositiveSmallIntegerField(choices=[(0, 'Playing'), (1, 'Exercise and Commute'), (2, 'Exercise and Commute and Lond Distance'), (3, 'Long Distance'), (4, 'Commute')], default=0)),
                ('mrp', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(199999)])),
            ],
        ),
    ]
