# Generated by Django 2.2.4 on 2019-08-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0002_auto_20190824_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (0, 'Female')], default=0),
        ),
    ]
